[package]
name = "mtxcli"
version = "0.2.1"
authors = ["Tom Marble <tmarble@info9.net>"]
edition = "2018"

[dependencies]
clap = "2.33"
log = "0.4"
yansi = "0.5"
flexi_logger = { version = "0.15", features = ["specfile", "colors"] }
