[package]
name = "mtxcli"
version = "0.3.0"
authors = ["Tom Marble <tmarble@info9.net>"]
edition = "2018"

[dependencies]
clap = "2.33"
log = "0.4"
yansi = "0.5"
flexi_logger = { version = "0.15", features = ["specfile", "colors"] }
mkdirp = "1.0"
serde_json = "1.0"
regex = "1.3"
